spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/catsDB
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
      #show_sql: true

logging.level:
  sql: trace

