spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/catsDB
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-batch-fetch-size: 100
        format_sql: true
        # show_sql: true

# batch:
# job:
# name: ${job.name:NONE}
# jdbc:
# initialize-schema: ALWAYS

jwt:
  issuer: "kim"
  secret-key: ""
  expire-second: ""

logging.level:
  # sql: trace
  org.hibernate.SQL: debug
